nexus:
  image: "sonatype/docker-nexus3"
  ports:
  - "${PORT}:8081"
  labels:
    io.rancher.sidekicks: "nexus-data"
    io.rancher.container.hostname_override: "container_name"
  volumes_from:
  - "nexus-data"
nexus-data:
  image: "busybox"
  volumes:
  - "${HOST_VOLUME}:/nexus-data"
  labels:
    io.rancher.container.start_once: true
  entrypoint: ["chown", "-R", "200:200", "/nexus-data"]
